### ISSUE TITLE
Make ZoomSettings Equatable conformance public

### ISSUE THREAD

**Issue by mennolovink** [mennolovink/Zoomy#23]
It's currently internal

**Comment by mennolovink** [comment]
Code was already public:
<img width="552" alt="screen shot 2018-04-18 at 12 46 15" src="https://user-images.githubusercontent.com/2656075/38927652-c2e9dc02-4306-11e8-9b32-76cb08f9f57d.png">

**Comment by nedimf** [comment]
Does this means we can control maximum zoom scale?

**Comment by lvnkmn** [comment]
Hi @nedimf sorry for not responding, I didn't get notifications for this repo for a while.
Maximum zoom scale can be controlled indeed (even before this issue was resolved).

`addZoombehavior(for: imageView, settings: Settings().with(maximumZoomScale: 5)` where 5 can be any other zoom scale
