### ISSUE TITLE
Need to zoom in 3rd layer like uitableview->uitableviewcell->collectionview->uicollectionviewcell's imageview

### ISSUE THREAD

**Issue by susheelopenxcell** [mennolovink/Zoomy#59]
I need to zoom an image from  uitabelview -> uitableviewcell -> collectionview -> uicollectionviewcell -> imageview. 

So i have to use  addZoombehavior(for: imageView) method in uitableviewcell and i cant access rightnow  so kindly help me to solve this.

**Comment by susheelopenxcell** [comment]
I am trying to access it from uitableviewcell.

*Susheel Parmar*
*SR. Software Engineer - iOS*
*Openxcell Technolabs Pvt. Ltd.*

**Comment by mennolovink** [comment]
If you'd like to acces it from the cell, here's the most direct way to achieve this:
Import Zoomy, make sure the tableviewcell conforms to `CanManageZoomBehaviors` and the `addZoomBehavior` method should be accessible. Hope this works for you!
